#!/usr/bin/env python3
"""Generate the advisory index and a rendered markdown page per advisory.

Reads every OSV-format advisory JSON (advisories/CGP-*/CGP-*.json) and writes:

- ADVISORIES.md — an index table with the ecosystem, package name, and affected
  version range, each row linking to the advisory's rendered page.
- docs/advisories/CGP-<id>.md — a readable page per advisory, built only from
  fields present in the JSON, linking back to the JSON source and patch files.

Nothing is computed or inferred; every value comes straight from the JSON.

Usage:
    python3 scripts/generate_advisory_list.py        # write the files
    python3 scripts/generate_advisory_list.py --check # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ADVISORIES_DIR = REPO_ROOT / "advisories"
INDEX_FILE = REPO_ROOT / "ADVISORIES.md"
PAGES_DIR = REPO_ROOT / "docs" / "advisories"

DASH = "—"

INDEX_HEADER = """# Advisory index

Generated by `scripts/generate_advisory_list.py` — do not edit by hand.
Run the script to regenerate after adding or changing advisories.

| Advisory | Ecosystem | Package | Introduced | Fixed |
|----------|-----------|---------|------------|-------|
"""


def rellink(target: Path, start_dir: Path) -> str:
    """POSIX relative link from a file in start_dir to target."""
    return os.path.relpath(target, start_dir).replace(os.sep, "/")


def iter_events(affected: dict, key: str) -> list[str]:
    """Collect all values for an event key (e.g. 'introduced') across ranges."""
    values = []
    for rng in affected.get("ranges", []):
        for event in rng.get("events", []):
            if key in event:
                values.append(event[key])
    return values


def load_advisories() -> list[tuple[Path, dict]]:
    """Load every advisory JSON, sorted by ecosystem, package name, then id."""
    advisories = []
    for path in ADVISORIES_DIR.glob("CGP-*/CGP-*.json"):
        advisories.append((path, json.loads(path.read_text())))

    def sort_key(item: tuple[Path, dict]):
        _, data = item
        first = (data.get("affected") or [{}])[0]
        package = first.get("package", {})
        return (
            package.get("ecosystem", "").lower(),
            package.get("name", "").lower(),
            data.get("id", ""),
        )

    advisories.sort(key=sort_key)
    return advisories


def page_path_for(data: dict, path: Path) -> Path:
    advisory_id = data.get("id", path.parent.name)
    return PAGES_DIR / f"{advisory_id}.md"


# --- index -----------------------------------------------------------------


def render_index(advisories: list[tuple[Path, dict]]) -> str:
    lines = [INDEX_HEADER.rstrip("\n")]
    for path, data in advisories:
        advisory_id = data.get("id", path.parent.name)
        page_link = rellink(page_path_for(data, path), REPO_ROOT)
        for affected in data.get("affected", []):
            package = affected.get("package", {})
            ecosystem = package.get("ecosystem", DASH)
            name = package.get("name", DASH)
            introduced = ", ".join(iter_events(affected, "introduced")) or DASH
            fixed = ", ".join(iter_events(affected, "fixed")) or DASH
            cells = (
                f"[{advisory_id}]({page_link})",
                ecosystem,
                f"`{name}`",
                introduced,
                fixed,
            )
            lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


# --- per-advisory page -----------------------------------------------------


def render_affected(affected: dict) -> list[str]:
    lines = []
    package = affected.get("package", {})
    ecosystem = package.get("ecosystem")
    name = package.get("name")
    purl = package.get("purl")
    introduced = ", ".join(iter_events(affected, "introduced"))
    fixed = ", ".join(iter_events(affected, "fixed"))

    if ecosystem:
        lines.append(f"- **Ecosystem:** {ecosystem}")
    if name:
        lines.append(f"- **Package:** `{name}`")
    if purl:
        lines.append(f"- **Package URL:** `{purl}`")
    if introduced:
        lines.append(f"- **Introduced:** {introduced}")
    if fixed:
        lines.append(f"- **Fixed:** {fixed}")

    specific = affected.get("database_specific", {})
    cwe_ids = specific.get("cwe_ids") or []
    if cwe_ids:
        lines.append(f"- **Weaknesses:** {', '.join(cwe_ids)}")

    sinks = specific.get("sink_locator") or []
    if sinks:
        lines.append("")
        lines.append("**Affected code:**")
        lines.append("")
        for sink in sinks:
            cls = sink.get("class", "")
            method = sink.get("method", "")
            file_line = sink.get("file_line", "")
            label = ".".join(part for part in (cls, method) if part)
            suffix = f" (`{file_line}`)" if file_line else ""
            lines.append(f"- `{label}`{suffix}" if label else f"- `{file_line}`")
    return lines


def render_page(path: Path, data: dict) -> str:
    advisory_id = data.get("id", path.parent.name)
    lines = [f"# {advisory_id}", ""]

    summary = data.get("summary")
    if summary:
        lines.append(summary)
        lines.append("")

    affected_list = data.get("affected", [])
    if affected_list:
        lines.append("## Affected packages")
        lines.append("")
        for index, affected in enumerate(affected_list):
            if index:
                lines.append("")
            lines.extend(render_affected(affected))
        lines.append("")

    severity = data.get("severity", [])
    if severity:
        lines.append("## Severity")
        lines.append("")
        for entry in severity:
            sev_type = entry.get("type", "")
            score = entry.get("score", "")
            lines.append(f"- **{sev_type}:** `{score}`")
        lines.append("")

    details = data.get("details")
    if details:
        lines.append("## Details")
        lines.append("")
        lines.append(details)
        lines.append("")

    # Sources: the JSON itself and any patch files in the advisory directory.
    lines.append("## Sources")
    lines.append("")
    json_link = rellink(path, PAGES_DIR)
    lines.append(f"- [Advisory JSON]({json_link})")
    for patch in sorted(path.parent.glob("*.patch")):
        lines.append(f"- [Patch: {patch.name}]({rellink(patch, PAGES_DIR)})")
    lines.append("")

    published = data.get("published")
    modified = data.get("modified")
    meta = [f"Published {published}" if published else "",
            f"Modified {modified}" if modified else ""]
    meta_line = " · ".join(part for part in meta if part)

    lines.append("---")
    lines.append("")
    footer = "Generated from the advisory JSON by `scripts/generate_advisory_list.py` — do not edit by hand."
    lines.append(f"{meta_line} · {footer}" if meta_line else footer)
    return "\n".join(lines) + "\n"


# --- orchestration ---------------------------------------------------------


def build_outputs() -> dict[Path, str]:
    """Return a mapping of output file path -> content for every generated file."""
    advisories = load_advisories()
    outputs: dict[Path, str] = {INDEX_FILE: render_index(advisories)}
    for path, data in advisories:
        outputs[page_path_for(data, path)] = render_page(path, data)
    return outputs


def check(outputs: dict[Path, str]) -> int:
    stale = []
    for path, content in outputs.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path)

    expected_pages = {p for p in outputs if p.parent == PAGES_DIR}
    orphans = {p for p in PAGES_DIR.glob("*.md")} - expected_pages if PAGES_DIR.exists() else set()

    if stale or orphans:
        for path in sorted(stale) + sorted(orphans):
            print(f"out of date: {path.relative_to(REPO_ROOT)}")
        print("Run scripts/generate_advisory_list.py to regenerate.")
        return 1
    print("Advisory index and pages are up to date.")
    return 0


def write(outputs: dict[Path, str]) -> int:
    PAGES_DIR.mkdir(parents=True, exist_ok=True)

    # Remove stale page files that no longer correspond to an advisory.
    expected_pages = {p for p in outputs if p.parent == PAGES_DIR}
    for existing in PAGES_DIR.glob("*.md"):
        if existing not in expected_pages:
            existing.unlink()

    for path, content in outputs.items():
        path.write_text(content)

    pages = len(expected_pages)
    print(f"Wrote {INDEX_FILE.name} and {pages} pages in {PAGES_DIR.relative_to(REPO_ROOT)}/.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any generated file is out of date instead of writing",
    )
    args = parser.parse_args()

    outputs = build_outputs()
    return check(outputs) if args.check else write(outputs)


if __name__ == "__main__":
    sys.exit(main())
